### ISSUE TITLE
Investigate mac warnings

### ISSUE THREAD

**Issue by spectranaut** [Igalia/acacia#187]
On mac I get a lot of warnings when I build -- do you get these @alice?

```
[6/14] Generating nodejs_acacia_axapi_wrap.cxx
/repos/AXAccess/include/acacia/mac/mac_data_types.h:40: Warning 503: Can't wrap 'operator =' unless renamed to a valid identifier.
```

**Comment by alice** [comment]
Yeah, that's just SWIG not wrapping `operator=` - i.e. I've used [operator overloading](https://en.cppreference.com/w/cpp/language/operators) on some data types which are exposed to SWIG, and SWIG won't wrap the overloaded operators unless we rename them (e.g. to `reassign()` or something). I should probably just add a warning suppression for them.
