### ISSUE TITLE
Per-type enums/constants for roles and attributes on Mac

### ISSUE THREAD

**Issue by alice** [Igalia/acacia#82]
The Mac `AXUIElement...` APIs all use strings, so you _can_ pass arbitrary strings to the Mac API methods, e.g.:

```js
let role = app.CopyStringAttributeValue('AXRole');
```

However, it would be helpful to have a collection of constants for [roles](https://developer.apple.com/documentation/applicationservices/axroleconstants_h/miscellaneous_defines?language=objc), and one for the [well-known attributes](https://developer.apple.com/documentation/applicationservices/axattributeconstants_h/miscellaneous_defines?language=objc) which give an indication of the type of the return value.

**Comment by spectranaut** [comment]
Can we close this @alice ?

**Comment by alice** [comment]
Yeah, I think this is a WONTFIX given the limitations of the SWIG bindings.
